- index.js
> routes_products-pagination

- src/app.js
- src/controllers/products.js
- src/routes/index.js
- src/routes/products/index.js
Basic route to obtain the products. Coded by pair programming metodology.
> basic route to obtain the products

- package.json
- src/controllers/categories.js
- src/controllers/products.js
- src/db.js
- src/routes/products/index.js
Add routes GET products by name.
> add routes GET products by name

- src/controllers/products.js
- src/routes/products/index.js
> add GET product by id

- src/controllers/products.js
refactor route GET products by name
> refactor route GET products by name

- src/controllers/products.js
add filter route GET products by category
> add filter route GET products by category

- src/controllers/categories.js
- src/controllers/products.js
- src/routes/products/index.js
> add route POST category

- src/controllers/categories.js
- src/controllers/products.js
> refactor route POST category

- src/controllers/categories.js
- src/controllers/products.js
- src/db.js
- src/routes/products/index.js
> add route POST product

- src/controllers/products.js
- src/routes/products/index.js
Realizadas las rutas de elimiar y modificar productos.
> Routes_Update-Delete-Product

- index.js
- src/controllers/categories.js
- src/controllers/categoriesLoader.js
- src/controllers/products.js
- src/controllers/productsLoader.js
> refactor_error_handling

- src/controllers/products.js
Add search by categoryId in getProducts
> add search by categoryId in getProducts

- src/controllers/products.js
- src/db.js
- src/models/Category.js
- src/models/User.js
fix: same errors in updateProduct and Category model
> fix: same errors in updateProduct and Category model

- src/routes/categories/index.js
- src/routes/index.js
- src/routes/products/index.js
> fix: routes modularization

- src/controllers/products.js
fix: error handler in getProductById
> fix: error handler in getProductById

- client/index.html
- index.js
- package.json
- src/app.js
- src/db.js
- src/routes/index.js
refc: configurations for heroku deploy
> refc: configurations for heroku deploy

- src/data/brands.json
> s2_src: add brands.json

- src/controllers/brandsLoader.js
- src/db.js
- src/models/Brands.js
s2_feat: add brands model and loader
> s2_feat: add brands model and loader

- index.js
> fix: index.js

- src/data/brands.json
- src/data/products.json
> fix: products.json

- src/controllers/products.js
Arreglado el error de la cantidad de paginas en el get products cuando se le pasa por params un categoryId.
> Controls_Fixing-getProducts

- src/controllers/products.js
filtrado de rango de precios añadido
> Controls price filter

- src/controllers/products.js
- src/db.js
items por pagina controlables por query, filtro por marca controlado por query
> Controls_filter-by-brand

- src/controllers/products.js
- src/models/Product.js
- src/routes/brands/index.js
- src/routes/packing/index.js
Deploy new features:
- Complete CRUD of Categories
- New filters in getProducts
> Deploy new features 09/09/2021

- package.json
pkg: moved nodemon to dependencies.
> pkg: moved nodemon to dependencies

- index.js
> fix: set force true

- index.js
- src/controllers/orders/carts.js
- src/controllers/orders/orders.js
- src/models/Order.js
- src/routes/carts/index.js
- src/routes/index.js
- src/routes/orders/index.js
> Alejandro orders

- src/controllers/user/favourites.js
- src/controllers/user/user.js
- src/db.js
- src/routes/products/index.js
agregadas todas las funcionalidades y tabla intermedia favoritos, lo hice como tabla intermedia etre products y user
> Favourites

- src/controllers/user/user.js
feat: added update admin and active field in user table.
> feat: added update admin and active field in user table.

- index.js
- package.json
- src/controllers/Review/review.js
- src/controllers/orders/carts.js
- src/controllers/products.js
- src/db.js
- src/models/Review.js
- src/routes/index.js
- src/routes/review/index.js
problema con imagenes en el carrito solventadas
> Fixing bugs

- src/controllers/user/user.js
Now return active field when create a new user.
> fix: now return active field
